### ISSUE TITLE
Please add labels to count as contribution

### ISSUE THREAD

**Issue by achoudh5** [Cyberkid2311/Hactoberfest-2020-Projects#37]
https://hacktoberfest.digitalocean.com/hacktoberfest-update

Hi 

Can you please add two labels:-

1. At you repo, main page-> `hacktoberfest` label

2. Closed PR's-> label->`hacktoberfest-accepted`

**Comment by Cyberkid2311** [comment]
Thanks for the info @achoudh5. I am regularly merging the codes i find useful and so You need not worry about your contribution it will be merged properly.
